folio-org/mod-circulation-item

Dockerfile

Run apk upgrade in Dockerfile to fix security vulnerabilities
Fixed the docker file with necessary call to apk upgrade command.

[MODCITEM-2] - Added apk upgrade command to docker file.

---

.dockerignore
Dockerfile
Jenkinsfile

https://issues.folio.org/browse/MODCITEM-3

MODCITEM-3: Fix jar in Dockerfile; add .dockerignore; fix Jenkinsfile

---

pom.xml
src/main/java/org/folio/circulation/item/controller/CirculationItemController.java
src/main/java/org/folio/circulation/item/controller/ExceptionHandlingController.java
src/main/java/org/folio/circulation/item/domain/mapper/CirculationItemMapper.java
src/main/java/org/folio/circulation/item/repository/CirculationItemRepository.java
src/main/java/org/folio/circulation/item/service/CirculationItemService.java
src/main/java/org/folio/circulation/item/service/impl/CirculationItemServiceImpl.java
src/main/java/org/folio/circulation/item/util/MapperUtils.java
src/main/java/org/folio/circulation/item/utils/ErrorHelper.java
src/main/resources/swagger.api/circulation-item.yaml
src/test/java/org/folio/circulation/item/controller/CirculationItemControllerTest.java
src/test/java/org/folio/circulation/item/service/CirculationItemServiceTest.java
src/test/java/org/folio/circulation/item/util/MapperUtilsTest.java
src/test/java/org/folio/circulation/item/utils/EntityUtils.java

Covers [MODCITEM-4](https://issues.folio.org/browse/MODCITEM-4)
In this PR implemented GET /circulation-item/barcode/{barcode} to GET circulation item by barcode API in mod-circulation-item.

MODCITEM-4 Create GET circulation item by barcode API

---

descriptors/ModuleDescriptor-template.json

https://issues.folio.org/browse/MODCITEM-5
Improve API POST-method json descriptor

MODCITEM-5: Improve API POST-method json descriptor

---

descriptors/ModuleDescriptor-template.json

Update the interface version of circulation-item

---

descriptors/ModuleDescriptor-template.json
pom.xml
src/main/java/org/folio/circulation/item/controller/CirculationItemController.java
src/main/java/org/folio/circulation/item/repository/CirculationItemRepository.java
src/main/java/org/folio/circulation/item/service/CirculationItemService.java
src/main/java/org/folio/circulation/item/service/impl/CirculationItemServiceImpl.java
src/main/resources/swagger.api/circulation-item.yaml
src/test/java/org/folio/circulation/item/controller/CirculationItemControllerTest.java
src/test/java/org/folio/circulation/item/utils/EntityUtils.java

[CIRC-1966](https://issues.folio.org/browse/CIRC-1966)

[CIRC-1966]-Api for supporting circulation change.

---

descriptors/ModuleDescriptor-template.json

[CIRC-1966]-Permission Fix

---

src/main/java/org/folio/circulation/item/service/impl/CirculationItemServiceImpl.java
src/test/java/org/folio/circulation/item/controller/CirculationItemControllerTest.java

MODCITEM-15 Adding barcode validation before creating item

---

src/main/resources/application.yml

https://issues.folio.org/browse/MODCITEM-21

MODCITEM-21: exposure:include: ${ACTUATOR_EXPOSURE:health,info,loggers}

---

src/main/java/org/folio/circulation/item/domain/entity/Item.java
src/main/java/org/folio/circulation/item/domain/mapper/CirculationItemMapper.java
src/main/resources/db/changelog/changes/add-lending-library-code.xml
src/main/resources/swagger.api/schemas/circulationItem.json
src/main/resources/swagger.api/schemas/item.yaml
src/test/java/org/folio/circulation/item/utils/EntityUtils.java

[MODCITEM-17](https://issues.folio.org/browse/MODCITEM-17)
Add lendingLibraryCode field to CirculationItem and lendingLibraryCode column to circulation_item table

MODCITEM-17

---

PERSONAL_DATA_DISCLOSURE.md

Added PERSONAL_DATA_DISCLOSURE.md file for TC evaluation
Added the new file.

[MODCITEM-20] - Added PERSONAL_DATA_DISCLOSURE.md file for TC

---

README.md

Covers: [MODCITEM-19](https://issues.folio.org/browse/MODCITEM-19)
Creating readme file

MODCITEM-19 Preparing readme file

---

MODULE_SELF_EVALUATION.md

Added MODULE_SELF_EVALUATION.md file for TCR process.

[TCR-37] - Added MODULE_SELF_EVALUATION.md file.

---

pom.xml
src/test/java/org/folio/circulation/item/controller/CirculationItemControllerTest.java

TCR-37 Changes made as per TC review comments

TCR-37 Changes made as per TC review comments

---

NEWS.md
pom.xml

[MODCITEM-27]-Q release 1.0.0

---

pom.xml

[MODCITEM-30] - Upgrade folio spring support version

---

.github/workflows/postgres.yml
pom.xml
src/test/java/org/folio/circulation/item/context/PostgresTestContainersBeanFactoryPostProcessor.java
src/test/java/org/folio/circulation/item/controller/BaseIT.java

[MODCITEM-32] - Upgrade versions

---

.github/workflows/postgres.yml
Dockerfile
Jenkinsfile
pom.xml

FOLIO-4232 - Spring and Java version upgrade

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml

Upgrade versions and NEWS.md file

---

.github/dependabot.yml
CODEOWNERS
PULL_REQUEST_TEMPLATE.md

- to have in place the process for automation of the updates of dependent modules
- to have standardized approach for all the Pull Requests created for the modules of volaris team
- for codeowners been automatically tagged in PRs
- add `dependabot.yml` config file
- update `PULL_REQUEST_TEMPLATE.md` file
- add `CODEOWNERS` file
[MODCITEM-40](https://folio-org.atlassian.net/browse/MODCITEM-40)

MODCITEM-40: Add config file for dependabot and template for pull request

---

src/main/java/org/folio/circulation/item/domain/mapper/CirculationItemMapper.java
src/test/java/org/folio/circulation/item/controller/CirculationItemControllerTest.java

_Describe the purpose of this pull request. Why is this change necessary? What problem does it solve?_
Set default effectiveLocationId in circ-item if not provided in request
[MODCITEM-41](https://folio-org.atlassian.net/browse/MODCITEM-41)
_List any Jira issues related to this pull request._
_Discuss any research conducted during the development of this pull request. Include links to relevant blog posts, patterns, libraries, or addons that were used to solve the problem._
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._

MODCITEM-41: set default effectiveLocationId in circ-item if not provided
